name: User Agent
addon_url: https://github.com/lesaff/statamic-useragent
version: 1.0.0
developer: Rudy Affandi
developer_url: https://github.com/lesaff
description: Get browser information (User agent, mobile/desktop detector, OS etc)